{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb"  }}
  labels:
    {{- include "jira-software.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.databaseConnection.password | b64enc | quote }}
{{- end }}
