apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jira-software.fullname" . }}-secret
  labels:
    {{- include "jira-software.labels" . | nindent 4 }}
type: Opaque
data:
  postgres_password: {{ .Values.databaseConnection.password }}