# Default values for jira.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# @Notes
# We must set resources requests and limits for preventing OOM killer

## Atlassian Jira Software image version
## ref: https://hub.docker.com/r/atlassian/jira-software
image:
  # registry: hub.docker.com
  repository: atlassian/jira-software
  tag: 8.21.0
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  pullSecrets: {}
  #   - myRegistryKeySecretName

## String to partially override jira.fullname template (will maintain the release name)
nameOverride: ""

## String to fully override jira.fullname template
fullnameOverride: ""

## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## ref: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#podsecuritycontext-v1-core
podSecurityContext:
  fsGroup: 2001

## Security context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext: {}
#  capabilities:
#    drop:
#    - ALL
#  readOnlyRootFilesystem: true
#  runAsNonRoot: true
#  runAsUser: 1000

## Service/Networking
## ref: https://kubernetes.io/docs/concepts/services-networking/service/
## Kubernetes svc configuration
service:
  ## For minikube, set this to NodePort, elsewhere use LoadBalancer
  type: ClusterIP
  ## Use serviceLoadBalancerIP to request a specific static IP, otherwise leave blank
  ##
  ## Avoid removing the http connector, as the Synchrony proxy health check, still requires HTTP
  ## HTTP Port, must be the same as ATL_TOMCAT_PORT (default: 8080)
  port: 8080
  ## HTTPS Port, in case ATL_TOMCAT_SCHEME is set to 'https'
  httpsPort: 8080
  loadBalancerIP:
  ## Use nodePorts to requets some specific ports when usin NodePort
  ## nodePorts:
  ##   http: <to set explicitly, choose port between 30000-32767>
  ##   https: <to set explicitly, choose port between 30000-32767>
  ##
  nodePorts:
    http:
    https:

## Configure the ingress resource that allows you to access the
## Jira installation. Set up the URL
## ref: http://kubernetes.io/docs/user-guide/ingress/
ingress:
  ## Set to true to enable ingress record generation
  enabled: true
  customResourceEnabled: false # use custom resource provided Ingress (not recommended because it uses old API version of Ingress)
  tlsEnabled: true
  tlsSecretName: "jira1.{{ .Values.domain }}"
  hostname: "jira1.{{ .Values.domain }}"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  path: "/"

domain: black.eurekacloud.io

## Resources. Mandatory, see @Notes above.
## ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 2Gi
    cpu: 1
  limits:
    memory: 4Gi
    cpu: 2

## Replication (without ReplicaSet)
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
replicaCount: 1

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

## Persistent Volume Claim
## Jira Home directory
## https://kubernetes.io/docs/concepts/storage/persistent-volumes/
persistence:
  enabled: true
  annotations: {}
  ## existingClaim needs the existing PVC name
  existingClaim: ""
  accessMode: ReadWriteOnce
  size: 10Gi

  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to nil, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass:
  storageClassCreate: false
  volumeName:

# Additional volume mounts
extraVolumeMounts: []
  ## Example: Mount CA file
  # - name: ca-cert
  #   subPath: ca_cert
  #   mountPath: /path/to/ca_cert

# Additional volumes
extraVolumes: []
  ## Example: Add secret volume
  # - name: ca-cert
  #   secret:
  #     secretName: ca-cert
  #     items:
  #     - key: ca-cert
  #       path: ca_cert

## Pull secrets for the DB connection from Vault  (here we use anchors, see databaseConnection)
## Change double-quoted values if enabled is set to 'true'
vaultSecrets:
  enabled: false
  secret: ""
  host: &host "${myvault.secrets.jira-software-db-host}"
  db: &db "${myvault.secrets.jira-software-db}"
  user: &db-user "${myvault.secrets.jira-software-db-user}"
  pw: &db-pw "${myvault.secrets.jira-software-db-pw}"

## Set up update strategy for Jira installation. Set to Recreate if you use persistent volume
## that cannot be mounted by more than one pods to make sure the pods is destroyed first.
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
updateStrategy: []
  # type: Recreate
#  type: RollingUpdate
#  rollingUpdate:
#    maxUnavailable: 25%
#    maxSurge: 25%

## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
schedulerName: ""

## Container Probes
## ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
## Depending what values we give, Jira won't be reachable. In doubt, leave it as it is.
readinessProbe: {}
  # httpGet:
  #   path: /status
  #   port: http
  # initialDelaySeconds: 300
  # periodSeconds: 30
  # failureThreshold: 6
  # timeoutSeconds: 10

livenessProbe: {}
  # httpGet:
  #   path: /status
  #   port: http
  # initialDelaySeconds: 480
  # periodSeconds: 30
  # failureThreshold: 6
  # timeoutSeconds: 10

##
## Postgresql chart configuration
## https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml
##
postgresql:
  ## Whether to deploy a postgres server to satisfy the applications database requirements.
  enabled: false

  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: "11"
    pullPolicy: IfNotPresent

  fullnameOverride: jira-software-db

  persistence:
    size: 20Gi

  initdbScriptsConfigMap: |-
    {{ .Release.Name }}-db-helper-cm

##
## If postgresql is enabled and no database exists, it will be created (see db-helper ConfigMap)
## by default, vaultSecret* are mapped here
## If vaultSecrets.enabled is false, replace values below in plaintext,
## password will be send to externaldb-secrets
##
## Aliases disabled, not using vaultSecrets anchors.
databaseConnection:
  ## Database host
  # host: *host
  host: postgres

  ## non-root Username for Jira Database
  # user: *db-user
  user: postgres

  ## Database password
  # password: *db-pw
  # encrypted value using sealedsecrets
  password: password

  ## Database name
  # database: *db
  database: jiradb

  ## lc_collate and lc_ctype, only in case database needs to be created
  lang: C

  ## Database port number
  port: 5432

  ## Jira specific database information
  ## https://hub.docker.com/r/atlassian/jira-software
  ## JDBC Prefix URL
  urlPrefix: "jdbc:postgresql"

  ## Database Driver
  ## https://hub.docker.com/r/atlassian/jira-software
  databaseDriver: "org.postgresql.Driver"

  ## Database Type
  ## https://hub.docker.com/r/atlassian/jira-software
  type: postgres72

  ##
  ## Database Schema Name
  ## https://hub.docker.com/r/atlassian/jira-software
  ## Depending of the type of the database, the Schema Name needs to be
  ## modified to one of the followings values:
  ## type: mssql      -> schemaName: dbo
  ## type: mysql      -> schemaName: public
  ## type: oracle10g  -> schemaName: NONE
  ## type: postgres72 -> schemaName: public
  schemaName: public

## DB DROP, use with caution!
## If postgresql.enabled is set to true and database exists, it will drop the db before creating a new one
## (see db-helper ConfigMap)
## This shouldn't be changed manually, instead run helm with --set databaseDrop.enabled=true --set databaseDrop.dropIt="yes"
## to be sure that you know what you are doing
databaseDrop:
  enabled: false
  dropIt: "no"

##
## Jira specific configurations
## https://hub.docker.com/r/atlassian/jira-software
## jira/secrets/cas
caCerts: {}
  # storepass: changeit # default keystore password
  # caCertsEnv:
#   - name: VARIABLE
#     value: my-value
#
## Environment Variables that will be injected in the ConfigMap
## Default values unless otherwise stated
envVars: 
  #
  ## Memory / Heap Size (JVM_MINIMUM_MEMORY) Mandatory, see @Notes above
  ## default: 1024m
  JVM_MINIMUM_MEMORY: 1024m
  ## Memory / Heap Size (JVM_MAXIMUM_MEMORY) Mandatory, see @Notes above
  ## default: 1024m
  JVM_MAXIMUM_MEMORY: 1024m
  ## The reserved code cache size of the JVM
  # JVM_RESERVED_CODE_CACHE_SIZE: 512m
  #
  ## Tomcat and Reverse Proxy Settings
  ## Jira running behind a reverse proxy server options
  # ATL_PROXY_NAME: ""
  # ATL_PROXY_PORT: ""
  # ATL_TOMCAT_PORT: 8080
  ATL_TOMCAT_SCHEME: https
  # ATL_TOMCAT_SECURE: false
  # ATL_TOMCAT_CONTEXTPATH: ""
  #
  ## Tomcat/Catalina options
  ## ref: https://tomcat.apache.org/tomcat-7.0-doc/config/index.html
  # ATL_TOMCAT_MGMT_PORT: 8005
  # ATL_TOMCAT_MAXTHREADS: 100
  # ATL_TOMCAT_MINSPARETHREADS: 10
  # ATL_TOMCAT_CONNECTIONTIMEOUT: 20000
  # ATL_TOMCAT_ENABLELOOKUPS: false
  # ATL_TOMCAT_PROTOCOL: "HTTP/1.1"
  # ATL_TOMCAT_ACCEPTCOUNT: 10
  # ATL_TOMCAT_MAXHTTPHEADERSIZE: 8192
  #
  ## Cookie age (Remember Me maximum time remain logged-in)
  # ATL_AUTOLOGIN_COOKIE_AGE: 1209600
  #
  ## Home directory. This may be on a mounted volume; if so it
  ## should be writable by the user jira. See note below about UID mappings.
  # JIRA_HOME: ""
  #
  ## Optional connection pool database settings
  # ATL_DB_MAXIDLE: 20
  # ATL_DB_MAXWAITMILLIS: 30000
  # ATL_DB_MINEVICTABLEIDLETIMEMILLIS: 5000
  # ATL_DB_MINIDLE: 10
  # ATL_DB_REMOVEABANDONED: true
  # ATL_DB_REMOVEABANDONEDTIMEOUT: 300
  # ATL_DB_TESTONBORROW: false
  # ATL_DB_TESTWHILEIDLE: true
  # ATL_DB_TIMEBETWEENEVICTIONRUNSMILLIS: 30000
  #
  ## Jira Data Center
  # CLUSTERED: true
  # JIRA_NODE_ID: node1
  # JIRA_SHARED_HOME: /var/atlassian/application-data/jira/shared/

## End of Environment Variables (envVars)

## JVM_SUPPORT_RECOMMENDED_ARGS
## Additional container environment variables
extraEnv:
  enabled: false
  parameters:
    # - -Djavax.net.ssl.trustStore=/var/atlassian/application-data/jira/cacerts
    # -XX:MaxMetaspaceSize: 512m
    # -XX:MaxDirectMemorySize: 10m
    # -Dsynchrony.memory.max: 0m

prometheusRule:
  enabled: false